.TH CLINFO 1 "2014-09-27" "clinfo 1.2.14.9.27"

.SH NAME

clinfo \- show OpenCL platforms and devices

.SH SYNOPSIS
.B clinfo

.SH DESCRIPTION
.B clinfo
prints all available information about all OpenCL platforms
available on the system and the devices they expose.

.SH OPTIONS
This program accepts no options.

.SH CONFORMING TO

OpenCL 1.1, OpenCL 1.2.

.SH EXTENSIONS

Supported OpenCL extensions:
.TP 2
.BR cl_khr_fp16 ", " cl_khr_fp64 ", " cl_amd_fp64 ", " cl_APPLE_fp64_basic_ops
for information about support for half-precision and double-precision
floating-point data types;
.TP
.B cl_khr_image2d_from_buffer
for information about the base address and pitch alignment requirements
of buffers to be used as base for 2D images;
.TP
.B cl_khr_spir
for information about the supported SPIR (Standard Portable Intermediate
Representation) versions;
.TP
.B cl_khr_icd
for the suffix of vendor extensions functions;
.TP
.B cl_ext_device_fission
for device fission support in OpenCL 1.1 devices;
.TP
.B cl_ext_atomic_counters_32
.TQ
.B cl_ext_atomic_counters_64
for the atomic counter extension;
.TP
.B cl_amd_device_attribute_query
for AMD-specific device attributes;
.TP
.B cl_nv_device_attribute_query
for NVIDIA-specific device attributes;
.TP
.B cl_intel_exec_by_local_thread
for the Intel extension allowing CPU devices to run kernels as part of
the current host thread;
.TP
.B cl_altera_device_temperature
for the Altera extension to query the core temperature of the device;
.TP
.B cl_qcom_ext_host_ptr
for the QUALCOMM extension to query page size and required padding in external
memory allocation.

.SH NOTES
Some information is duplicated when available from multiple sources.
Examples:
.IP \(bu 2
supported device partition types and domains as obtained using the
.B cl_ext_device_fission
extension typically match the ones obtained using
the core OpenCL 1.2 device partition feature;
.IP \(bu
the preferred work-group size multiple matches the NVIDIA warp size (on
NVIDIA devices) or the AMD wavefront width (on AMD devices).

.P
Some floating-point configuration flags may only be meaningful for
specific precisions and/or specific OpenCL versions. For example,
.B CL_FP_CORRECTLY_ROUNDED_DIVIDE_SQRT
is only relevant for single precision in OpenCL 1.2 devices.

.SH BUGS
The results of the following undocumented properties might be
interpreted incorrectly:
.IP \(bu 2
.B CL_DEVICE_GLOBAL_FREE_MEMORY_AMD

.P
Please report any issues on
.UR http://github.com/Oblomov/clinfo
the project tracker on GitHub
.UE .

